# Generated by Django 3.2.14 on 2022-10-01 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('support', 'support'), ('detail', 'detail'), ('dimension', 'dimension')], max_length=100),
        ),
    ]
