# Generated by Django 3.2.14 on 2022-10-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_guide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
